[localhost]
localhost
[frontend]
frontend.banasurekha.shop
[mongodb]
mongodb.banasurekha.shop
[catalogue]
catalogue.banasurekha.shop
[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
[redis]
redis.banasurekha.shop
[user]
user.banasurekha.shop
[cart]
cart.banasurekha.shop
[mysql]
mysql.banasurekha.shop
[shipping]
shipping.banasurekha.shop
[rabitmq]
rabitmq.banasurekha.shop