- name: configure {{ component }}
  become: yes
  #hosts: "{{ component }}"
  hosts: localhost
  connection: local
  roles: # this will auto matically load a folder called roles in current working directory
  -  "{{ component }}"